In [5]:
#to create a 1D numpy array, use a 1D list viz.

import numpy as np
ls = [1, 2, 3]
arr = np.array(ls) #this creates a 1D numpy array since we have passed ls list which is a 1D structure in python
print(arr) #printing the created 1D numpy array

[1 2 3]


In [6]:
#to create a 2D numpy array, use a 2D list viz.

import numpy as np
ls = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(ls) #this creates a 2D numpy array since we have passed ls list which is a 2D structure in python
print(arr) #printing the created 2D numpy array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#numpy .arange() function

'''
The .arange() function in numpy is very similar to the range function in python
The .arange() function automatically creates the numpy array and has the same parameters as the range function, ie; start, stop and step
Note that here too, the last value in the stop parameter is not inclusive just like the range fuction properties
'''

import numpy as np
data = np.arange(0, 10, 2)
print(data)

[0 2 4 6 8]
