In [1]:
#to create a 1D numpy array, use a 1D list viz.

import numpy as np
ls = [1, 2, 3]
arr = np.array(ls) #this creates a 1D numpy array since we have passed ls list which is a 1D structure in python
print(arr) #printing the created 1D numpy array

[1 2 3]


In [4]:
#to create a 2D numpy array, use a 2D list viz.

import numpy as np
ls = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(ls) #this creates a 2D numpy array since we have passed ls list which is a 2D structure in python
print(arr) #printing the created 2D numpy array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#numpy .arange() function

'''
The .arange() function in numpy is very similar to the range function in python
The .arange() function automatically creates the numpy array and has the same parameters as the range function, ie; start, stop and step
Note that here too, the last value in the stop parameter is not inclusive just like the range fuction properties
'''

import numpy as np
data = np.arange(0, 10, 2)
print(data)

[0 2 4 6 8]


In [20]:
#creating special types of numpy arrays

import numpy as np

data1 = np.zeros(3) #creates a numpy array with only zeroes, here we will have a single 1D array with 3 zeroes

data2 = np.zeros((2, 3)) #creates a numpy array again only with zeroes, but with a 2D framework. Here we mention the rows, columns; ie; r, c. This case we have 2 rows and 3 columns

print(data1)

print()

print(data2)

data3 = np.ones(3) #creates a numpy array with only ones, here we will have a single 1D array with 3 ones

data4 = np.ones((2, 3)) #creates a numpy array again only with ones, but with a 2D framework. Here we mention the rows, columns; ie; r, c. This case we have 2 rows and 3 columns

print()
print()

print(data3)

print()

print(data4)


[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


[1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
#using the .linspace() function

'''
The .linspace() function of numpy returns a 1D array of the evenly spaced points (no. of evenly spaced points generated = number passed as the
paramater with stop). This function generates the evenly spaced points between the start and stop, inclusive of both start and stop.
'''

import numpy as np

data = np.linspace(0, 5, 100) #this statement will generate a 1D numpy array with 100 evenly spaced points bewteen 0 to 5, including both 0 and 5

print(data)

[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3.53535354 3.58585859
 3.63636364 3.68686869 3.73737374 3.78787879 3.83838384 3.88888889
 3.93939394 3.98989899 4.04040404 4.09090909 4.14141414 4.19191919
 4.24242424 4.29292929 4.34343434 4.39393939 4.44444444 4.4949

In [25]:
#identity matrix using .eye() function of numpy. Mention the order of the matrix within the function paranthesis
#returns a 2D square matrix

import numpy as np

identity = np.eye(4) #generates a 2D identity matrix of order = 4

print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#generating random numbers arrays in numpy

import numpy as np

data1 = np.random.rand(5) #.rand() returns random numbers between 0 to 1. Here it gives 5 random numbers between 0 to 1. Gives 1D matrix

data2 = np.random.rand(5,5) #.rand(a, b) does the same thing, but as a 5x5 2D matrix. The matrix entries are still numbers b/w 0 to 1

print(data1)

print()

print(data2)

print()
print()

data3 = np.random.randn(5) #.rand() returns random numbers between the standard numbers. Here it gives 5 random numbers from the number line. Gives 1D matrix

data4 = np.random.randn(5,5) #.rand(a, b) does the same thing, but as a 5x5 2D matrix. The matrix entries are still random numbers from the number line

print(data3)

print()

print(data4)

print()
print()

#.randint(low, high, size) - the .randint() function generates random integers between the low to high interval.
#its inclusive of the low and exclusive of the high. The size is the number of random number you wish to generate

data5 = np.random.randint(5) #returns one random integer between 0 to 5, including 0 and exculding 5

data6 = np.random.randint(1, 100, 10) #return 10 random integers between 1 to 100, including 1 and exculding 100. Returns a 1D array

print(data5)

print()

print(data6)

[0.42200285 0.14950351 0.50431218 0.49407031 0.52440267]

[[0.26136178 0.53190396 0.14300564 0.11017908 0.84712174]
 [0.1832706  0.4024465  0.83858495 0.73902852 0.81954851]
 [0.10095411 0.35124007 0.29809728 0.44441788 0.76730241]
 [0.60556577 0.66245658 0.64860831 0.19591238 0.04667276]
 [0.52032448 0.13234848 0.52501255 0.48520936 0.76461783]]


[ 0.01555911  2.36536034 -0.14858666  0.46058065 -0.98548847]

[[-0.23378855  1.52470393  0.96804354  0.88972853  0.28407547]
 [ 1.1793526  -1.01539734  0.49438438  0.99365552 -0.71631553]
 [-0.57353055  0.3945485   1.30399114  3.34783386 -0.25951354]
 [-1.47441461 -1.99169077  0.86258284  0.1433539  -0.1592464 ]
 [ 0.14228341 -0.85334528 -0.15746772 -0.68166384 -0.4931895 ]]


4

[47 57 21  6 58 87 35 47 56 77]


In [36]:
#.reshape() array function in numpy

import numpy as np

arr = np.arange(25)

shaped = arr.reshape(5, 5) #.reshape(r, c); where r is the number of rows and c is the number of columns. Thus, it returns a 2D array

'''
Note that the python interpreter throws an error if the number of elements in the array you wish to reshape != r*c product
'''

print(shaped)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [48]:
#max, min values and their location in the array

import numpy as np

ranarr = np.random.randint(0, 50, 10)

max = ranarr.max()
min = ranarr.min()

print(max)
print(min)

print()
#to know the index location of the max and min values, use .argmax() and .argmin() functions viz.
print()

max_id = ranarr.argmax()
min_id = ranarr.argmin()

print(max_id)
print(min_id)

41
1


2
4


In [54]:
#.shape method to get to know the schema/type of the array/matrix

import numpy as np

arr = np.arange(25)

print(arr.shape) #will give (25,), which is a 1D matrix

arr = arr.reshape(5, 5)

arr.shape #will give (5, 5), indicating a 2D matirx of order 5x5

(25,)


(5, 5)

In [59]:
#.dtype method to get to know what datatypes you have in your array

import numpy as np

arr = np.arange(25)

arr.dtype

dtype('int32')

In [73]:
#indexing and selection of numpy arrays

import numpy as np

arr = np.arange(0, 11)

print(arr)

print(arr[8])
print(arr[1:5])
print()
print()

arr2D = np.array(ls)

print(arr2D)

#there are two ways to access the elements of teh 2D array. Firstly, the regular 2 brackets way we have been doing so far with lists and tuples
#and the second way it to use comma within one single bracket
#basically, in the former way, we did something like ls[5][4], so here we use comma instead viz; ls[5, 4]
#hence in numpy arrays alone, arr[5][4] == ls[5, 4]
print()

print(arr2D[1, 2])

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4]


[[1 2 3]
 [4 5 6]
 [7 8 9]]

6


In [10]:
#accesssing sub-sections of a numpy matrix/array

import numpy as np

ls = [[5, 10, 15], [20, 25, 30], [35, 40, 45]]

arr_2D = np.array(ls)   

print(arr_2D)
print()

#now say we don't want to slice a particular element off the array or display a set of elements in order, but just wish to have like a bunch of elements
#say i need to access elements 10, 15, 25, 30. How would I do that?

#to do so -

print(arr_2D[:2, 1:]) #basically it meant, rows starting from 0 upto row 1 (ie, 2-1=1) and columns starting from 1 till then end.

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

[[10 15]
 [25 30]]


In [23]:
#numpy operations

# ~ Array with Array operations
# ~ Array with Scalars operations
# ~ Universal Array Functions


import numpy as np

arr = np.arange(0, 11)

print(arr)
print(arr+arr)
print(arr-arr)
print(arr+100)
print(arr*100)
print(arr**2)
print(arr/100)
print(arr//100)
print(arr%2)
print(arr*arr)
print(arr**arr)
print(arr/arr)
print(arr//arr)

print()
print()

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))
print(np.sinh(arr))
print(np.cosh(arr))
print(np.log(arr))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[100 101 102 103 104 105 106 107 108 109 110]
[   0  100  200  300  400  500  600  700  800  900 1000]
[  0   1   4   9  16  25  36  49  64  81 100]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
[0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 1 0 1 0 1 0 1 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[         1          1          4         27        256       3125
      46656     823543   16777216  387420489 1410065408]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[0 1 1 1 1 1 1 1 1 1 1]


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.4121

C:\Users\mahaw\AppData\Local\Temp\ipykernel_6352\37626356.py:26: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)
C:\Users\mahaw\AppData\Local\Temp\ipykernel_6352\37626356.py:27: RuntimeWarning: divide by zero encountered in floor_divide
  print(arr//arr)
C:\Users\mahaw\AppData\Local\Temp\ipykernel_6352\37626356.py:39: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))
